name: 'build'

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Do you want to launch javascript build? [Y/n]'
        required: true
        default: 'Y'
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.scss'
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'yarn.lock'
  push:
    paths:
      - '**/*.js'
      - '**/*.scss'
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'yarn.lock'

jobs:
  javascript-build:
    name: 'Check javascript build'
    if: "github.event.inputs.build == 'Y'"
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: 'Checkout current revision'
        uses: 'actions/checkout@v3'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Yarn install'
        run: 'yarn install'

      - name: 'Yarn build'
        run: 'yarn build'

      - name: 'Run ESLint'
        run: 'yarn eslint frontend/**/*.js'
